* Parenting
** At the Restaurant
*** Toilets
When my wife and I took our two-year-old to a lovely little tea shop on 2023-02-15, he behaved himself like a complete gentleman. He said "please", and "thank you", and was a delight to be around. He stirred the milk into his tea and drank it very politely, asking nicely for more until he had consumed an entire pot. Needless to say, he soon had to use the toilet. We didn't think to scope out the toilet beforehand, and he was so frightened by the experience that he didn't go potty. Instead, he cried and partially voided his bladder into his "big boy" underpants. We made two mistakes: (1) We did not adequately prepare for the toilet situation at the tea shop, and (2) we did not preemptively have him wear a pull-up "just in case". That trip, we learned our lesson.

Make sure that when you go to a restaurant you have scoped out the toilets and assessed the situation based upon how your child(ren) will react. For example: Adults might like to have music a loud fan, and some sort of scent disperser to mask the noise and odor associated with using the toilet, but it might be intimidating for a child. Likewise, adults might prefer to have a dimly-lit atmosphere, but children might be used to using the toilet in a well-lit environment. Unusual sights, smells, and sounds can be frightening for a child, so they should be considered by parents before taking their child(ren) to the toilet in a restaurant. Occasionally, this can be ameliorated by preparing the child(ren) in advance, but this is no guarantee. Tread cautiously!
